import type { AtsSource, SourceScope } from "./types";

export type SourceRunMode = "core" | "daily" | "full";

type SourceDefinition = Omit<AtsSource, "scope">;

function scoped(scope: SourceScope, sources: readonly SourceDefinition[]): readonly AtsSource[] {
  return sources.map((source) => ({ ...source, scope }));
}

// Public employer job boards. Tokens are the final path component of each
// employer's hosted ATS board, not credentials.
export const CORE_ATS_SOURCES = scoped("core", [
  { id: "ashby-revenuecat", name: "RevenueCat", provider: "ashby", token: "revenuecat", website: "https://www.revenuecat.com" },
  { id: "ashby-kit", name: "Kit", provider: "ashby", token: "kit", website: "https://kit.com" },
  { id: "ashby-givebutter", name: "Givebutter", provider: "ashby", token: "givebutter", website: "https://givebutter.com" },
  { id: "ashby-archy", name: "Archy", provider: "ashby", token: "Archy", website: "https://www.archy.com" },
  { id: "ashby-somethings", name: "Somethings", provider: "ashby", token: "somethings" },
  { id: "ashby-infracost", name: "Infracost", provider: "ashby", token: "infracost", website: "https://www.infracost.io" },
  { id: "ashby-builder-prime", name: "Builder Prime", provider: "ashby", token: "builder-prime", website: "https://www.builderprime.com" },
  { id: "ashby-viz-ai", name: "Viz.ai", provider: "ashby", token: "Viz.ai", website: "https://www.viz.ai" },
  { id: "ashby-prompt", name: "Prompt", provider: "ashby", token: "prompt" },
  { id: "ashby-coder", name: "Coder", provider: "ashby", token: "coder", website: "https://coder.com" },
  { id: "ashby-gc-ai", name: "GC AI", provider: "ashby", token: "gc-ai", website: "https://gc.ai" },
  { id: "ashby-goody", name: "Goody", provider: "ashby", token: "goody", website: "https://www.ongoody.com" },
  { id: "ashby-highlightta", name: "Zipline", provider: "ashby", token: "highlightta", website: "https://getzipline.com" },
  { id: "ashby-jordan-digital", name: "Jordan Digital Marketing", provider: "ashby", token: "jordandigitalmarketing" },
  { id: "ashby-cloudzero", name: "CloudZero", provider: "ashby", token: "CloudZero", website: "https://www.cloudzero.com" },
  { id: "ashby-counsel", name: "Counsel Health", provider: "ashby", token: "counsel" },
  { id: "ashby-airwallex", name: "Airwallex", provider: "ashby", token: "airwallex", website: "https://www.airwallex.com" },
  { id: "ashby-socure", name: "Socure", provider: "ashby", token: "socure", website: "https://www.socure.com" },
  { id: "greenhouse-workleap", name: "Workleap", provider: "greenhouse", token: "workleap", website: "https://workleap.com" },
  { id: "greenhouse-wayvia", name: "Wayvia", provider: "greenhouse", token: "wayvia" },
  { id: "greenhouse-cresta", name: "Cresta", provider: "greenhouse", token: "cresta", website: "https://cresta.com" },
  { id: "greenhouse-maxwell", name: "Maxwell", provider: "greenhouse", token: "maxwell" },
  { id: "greenhouse-anthropic", name: "Anthropic", provider: "greenhouse", token: "anthropic", website: "https://www.anthropic.com" },
  { id: "greenhouse-commvault", name: "Commvault", provider: "greenhouse", token: "commvault", website: "https://www.commvault.com" },
  { id: "greenhouse-fsastore", name: "Health-E Commerce", provider: "greenhouse", token: "fsastorecom" },
  { id: "greenhouse-xapo", name: "Xapo Bank", provider: "greenhouse", token: "xapo61", website: "https://www.xapobank.com" },
  { id: "greenhouse-quip", name: "quip", provider: "greenhouse", token: "quip", website: "https://www.getquip.com" },
  { id: "greenhouse-honeycomb", name: "Honeycomb", provider: "greenhouse", token: "honeycomb", website: "https://www.honeycomb.io" },
  { id: "greenhouse-prolific", name: "Prolific", provider: "greenhouse", token: "prolific", website: "https://www.prolific.com" },
  { id: "greenhouse-figma", name: "Figma", provider: "greenhouse", token: "figma", website: "https://www.figma.com" },
  { id: "greenhouse-webflow", name: "Webflow", provider: "greenhouse", token: "webflow", website: "https://webflow.com" },
  { id: "greenhouse-cloudflare", name: "Cloudflare", provider: "greenhouse", token: "cloudflare", website: "https://www.cloudflare.com" },
]);

// Larger boards are isolated to the once-daily deep scrape. Each token is
// validated against the provider's public API before it is admitted here.
export const DAILY_ATS_SOURCES = scoped("daily", [
  { id: "greenhouse-reddit", name: "Reddit", provider: "greenhouse", token: "reddit", website: "https://www.redditinc.com" },
  { id: "greenhouse-coinbase", name: "Coinbase", provider: "greenhouse", token: "coinbase", website: "https://www.coinbase.com" },
  { id: "greenhouse-datadog", name: "Datadog", provider: "greenhouse", token: "datadog", website: "https://www.datadoghq.com" },
  { id: "greenhouse-mongodb", name: "MongoDB", provider: "greenhouse", token: "mongodb", website: "https://www.mongodb.com" },
  { id: "greenhouse-elastic", name: "Elastic", provider: "greenhouse", token: "elastic", website: "https://www.elastic.co" },
  { id: "greenhouse-grafana-labs", name: "Grafana Labs", provider: "greenhouse", token: "grafanalabs", website: "https://grafana.com" },
  { id: "greenhouse-gitlab", name: "GitLab", provider: "greenhouse", token: "gitlab", website: "https://about.gitlab.com" },
  { id: "greenhouse-samsara", name: "Samsara", provider: "greenhouse", token: "samsara", website: "https://www.samsara.com" },
  { id: "greenhouse-lyft", name: "Lyft", provider: "greenhouse", token: "lyft", website: "https://www.lyft.com" },
  { id: "greenhouse-airbnb", name: "Airbnb", provider: "greenhouse", token: "airbnb", website: "https://www.airbnb.com" },
  { id: "greenhouse-pinterest", name: "Pinterest", provider: "greenhouse", token: "pinterest", website: "https://www.pinterest.com" },
  { id: "greenhouse-khan-academy", name: "Khan Academy", provider: "greenhouse", token: "khanacademy", website: "https://www.khanacademy.org" },
  { id: "greenhouse-duolingo", name: "Duolingo", provider: "greenhouse", token: "duolingo", website: "https://www.duolingo.com" },
  { id: "greenhouse-twilio", name: "Twilio", provider: "greenhouse", token: "twilio", website: "https://www.twilio.com" },
  { id: "greenhouse-okta", name: "Okta", provider: "greenhouse", token: "okta", website: "https://www.okta.com" },
  { id: "greenhouse-asana", name: "Asana", provider: "greenhouse", token: "asana", website: "https://asana.com" },
  { id: "greenhouse-scale-ai", name: "Scale AI", provider: "greenhouse", token: "scaleai", website: "https://scale.com" },
  { id: "greenhouse-discord", name: "Discord", provider: "greenhouse", token: "discord", website: "https://discord.com" },
  { id: "greenhouse-klaviyo", name: "Klaviyo", provider: "greenhouse", token: "klaviyo", website: "https://www.klaviyo.com" },
  { id: "greenhouse-intercom", name: "Intercom", provider: "greenhouse", token: "intercom", website: "https://www.intercom.com" },
  { id: "greenhouse-databricks", name: "Databricks", provider: "greenhouse", token: "databricks", website: "https://www.databricks.com" },
  { id: "greenhouse-airtable", name: "Airtable", provider: "greenhouse", token: "airtable", website: "https://www.airtable.com" },
  { id: "greenhouse-instacart", name: "Instacart", provider: "greenhouse", token: "instacart", website: "https://www.instacart.com" },
  { id: "greenhouse-calendly", name: "Calendly", provider: "greenhouse", token: "calendly", website: "https://calendly.com" },
  { id: "greenhouse-dropbox", name: "Dropbox", provider: "greenhouse", token: "dropbox", website: "https://www.dropbox.com" },
  { id: "ashby-openai", name: "OpenAI", provider: "ashby", token: "openai", website: "https://openai.com" },
  { id: "ashby-linear", name: "Linear", provider: "ashby", token: "linear", website: "https://linear.app" },
  { id: "ashby-ramp", name: "Ramp", provider: "ashby", token: "ramp", website: "https://ramp.com" },
  { id: "ashby-cursor", name: "Cursor", provider: "ashby", token: "cursor", website: "https://www.cursor.com" },
  { id: "ashby-perplexity", name: "Perplexity", provider: "ashby", token: "perplexity", website: "https://www.perplexity.ai" },
  { id: "ashby-harvey", name: "Harvey", provider: "ashby", token: "harvey", website: "https://www.harvey.ai" },
  { id: "ashby-supabase", name: "Supabase", provider: "ashby", token: "supabase", website: "https://supabase.com" },
  { id: "ashby-replit", name: "Replit", provider: "ashby", token: "replit", website: "https://replit.com" },
  { id: "ashby-notion", name: "Notion", provider: "ashby", token: "notion", website: "https://www.notion.com" },
  { id: "ashby-elevenlabs", name: "ElevenLabs", provider: "ashby", token: "elevenlabs", website: "https://elevenlabs.io" },
  { id: "ashby-hex", name: "Hex", provider: "ashby", token: "hex", website: "https://hex.tech" },
  { id: "ashby-dust", name: "Dust", provider: "ashby", token: "dust", website: "https://dust.tt" },
  { id: "ashby-deepgram", name: "Deepgram", provider: "ashby", token: "deepgram", website: "https://deepgram.com" },
  { id: "lever-spotify", name: "Spotify", provider: "lever", token: "spotify", website: "https://www.spotify.com" },
  { id: "lever-palantir", name: "Palantir", provider: "lever", token: "palantir", website: "https://www.palantir.com" },
  { id: "greenhouse-toast", name: "Toast", provider: "greenhouse", token: "toast" },
  { id: "greenhouse-anduril", name: "Anduril", provider: "greenhouse", token: "andurilindustries" },
  { id: "greenhouse-roku", name: "Roku", provider: "greenhouse", token: "roku" },
  { id: "greenhouse-epic-games", name: "Epic Games", provider: "greenhouse", token: "epicgames" },
  { id: "greenhouse-geotab", name: "Geotab", provider: "greenhouse", token: "geotab" },
  { id: "greenhouse-fastly", name: "Fastly", provider: "greenhouse", token: "fastly" },
  { id: "greenhouse-stripe", name: "Stripe", provider: "greenhouse", token: "stripe" },
  { id: "greenhouse-chime", name: "Chime", provider: "greenhouse", token: "chime" },
  { id: "greenhouse-netskope", name: "Netskope", provider: "greenhouse", token: "netskope" },
  { id: "greenhouse-box", name: "Box", provider: "greenhouse", token: "boxinc" },
  { id: "greenhouse-axonius", name: "Axonius", provider: "greenhouse", token: "axonius" },
  { id: "greenhouse-pagerduty", name: "PagerDuty", provider: "greenhouse", token: "pagerduty" },
  { id: "greenhouse-robinhood", name: "Robinhood", provider: "greenhouse", token: "robinhood" },
  { id: "greenhouse-applovin", name: "AppLovin", provider: "greenhouse", token: "applovin" },
  { id: "greenhouse-trade-desk", name: "The Trade Desk", provider: "greenhouse", token: "thetradedesk" },
  { id: "greenhouse-stackadapt", name: "StackAdapt", provider: "greenhouse", token: "stackadapt" },
  { id: "greenhouse-pendo", name: "Pendo", provider: "greenhouse", token: "pendo" },
  { id: "greenhouse-mercury", name: "Mercury", provider: "greenhouse", token: "mercury" },
  { id: "greenhouse-checkr", name: "Checkr", provider: "greenhouse", token: "checkr" },
  { id: "greenhouse-zoominfo", name: "ZoomInfo", provider: "greenhouse", token: "zoominfo" },
  { id: "greenhouse-peloton", name: "Peloton", provider: "greenhouse", token: "peloton" },
  { id: "greenhouse-amplitude", name: "Amplitude", provider: "greenhouse", token: "amplitude" },
  { id: "greenhouse-heygen", name: "HeyGen", provider: "greenhouse", token: "heygen" },
  { id: "greenhouse-collibra", name: "Collibra", provider: "greenhouse", token: "collibra" },
  { id: "greenhouse-stackcommerce", name: "StackCommerce", provider: "greenhouse", token: "stackcommerce" },
  { id: "greenhouse-udacity", name: "Udacity", provider: "greenhouse", token: "udacity" },
  { id: "greenhouse-braze", name: "Braze", provider: "greenhouse", token: "braze" },
  { id: "greenhouse-brex", name: "Brex", provider: "greenhouse", token: "brex" },
  { id: "greenhouse-justworks", name: "Justworks", provider: "greenhouse", token: "justworks" },
  { id: "greenhouse-affirm", name: "Affirm", provider: "greenhouse", token: "affirm" },
  { id: "greenhouse-roblox", name: "Roblox", provider: "greenhouse", token: "roblox" },
  { id: "greenhouse-tripadvisor", name: "Tripadvisor", provider: "greenhouse", token: "tripadvisor" },
  { id: "greenhouse-vercel", name: "Vercel", provider: "greenhouse", token: "vercel" },
  { id: "greenhouse-mixpanel", name: "Mixpanel", provider: "greenhouse", token: "mixpanel" },
  { id: "greenhouse-coreweave", name: "CoreWeave", provider: "greenhouse", token: "coreweave" },
  { id: "greenhouse-bill", name: "BILL", provider: "greenhouse", token: "billcom" },
  { id: "greenhouse-workato", name: "Workato", provider: "greenhouse", token: "workato" },
  { id: "greenhouse-rubrik", name: "Rubrik", provider: "greenhouse", token: "rubrik" },
  { id: "greenhouse-attentive", name: "Attentive", provider: "greenhouse", token: "attentive" },
  { id: "greenhouse-kikoff", name: "Kikoff", provider: "greenhouse", token: "kikoff" },
  { id: "greenhouse-maven-clinic", name: "Maven Clinic", provider: "greenhouse", token: "mavenclinic" },
  { id: "greenhouse-commercetools", name: "commercetools", provider: "greenhouse", token: "commercetools" },
  { id: "greenhouse-launchdarkly", name: "LaunchDarkly", provider: "greenhouse", token: "launchdarkly" },
  { id: "greenhouse-marqeta", name: "Marqeta", provider: "greenhouse", token: "marqeta" },
  { id: "greenhouse-betterment", name: "Betterment", provider: "greenhouse", token: "betterment" },
  { id: "greenhouse-carta", name: "Carta", provider: "greenhouse", token: "carta" },
  { id: "greenhouse-new-relic", name: "New Relic", provider: "greenhouse", token: "newrelic" },
  { id: "greenhouse-culture-amp", name: "Culture Amp", provider: "greenhouse", token: "cultureamp" },
  { id: "greenhouse-postman", name: "Postman", provider: "greenhouse", token: "postman" },
  { id: "greenhouse-twitch", name: "Twitch", provider: "greenhouse", token: "twitch" },
  { id: "greenhouse-gusto", name: "Gusto", provider: "greenhouse", token: "gusto" },
  { id: "greenhouse-faire", name: "Faire", provider: "greenhouse", token: "faire" },
  { id: "greenhouse-algolia", name: "Algolia", provider: "greenhouse", token: "algolia" },
  { id: "greenhouse-cockroach-labs", name: "Cockroach Labs", provider: "greenhouse", token: "cockroachlabs" },
  { id: "greenhouse-contentful", name: "Contentful", provider: "greenhouse", token: "contentful" },
  { id: "greenhouse-hootsuite", name: "Hootsuite", provider: "greenhouse", token: "hootsuite" },
  { id: "greenhouse-sprout-social", name: "Sprout Social", provider: "greenhouse", token: "sproutsocial" },
  { id: "greenhouse-bombas", name: "Bombas", provider: "greenhouse", token: "bombas" },
  { id: "greenhouse-glossier", name: "Glossier", provider: "greenhouse", token: "glossier" },
  { id: "greenhouse-careem", name: "Careem", provider: "greenhouse", token: "careem" },
  { id: "greenhouse-sofi", name: "SoFi", provider: "greenhouse", token: "sofi" },
  { id: "greenhouse-bloomreach", name: "Bloomreach", provider: "greenhouse", token: "bloomreach" },
  { id: "greenhouse-salesloft", name: "Salesloft", provider: "greenhouse", token: "salesloft" },
  { id: "greenhouse-komodo-health", name: "Komodo Health", provider: "greenhouse", token: "komodohealth" },
  { id: "greenhouse-d2l", name: "D2L", provider: "greenhouse", token: "d2l" },
  { id: "greenhouse-udemy", name: "Udemy", provider: "greenhouse", token: "udemy" },
  { id: "greenhouse-assemblyai", name: "AssemblyAI", provider: "greenhouse", token: "assemblyai" },
  { id: "greenhouse-upwork", name: "Upwork", provider: "greenhouse", token: "upwork" },
  { id: "greenhouse-seekout", name: "SeekOut", provider: "greenhouse", token: "seekout" },
  { id: "greenhouse-descript", name: "Descript", provider: "greenhouse", token: "descript" },
  { id: "ashby-snowflake", name: "Snowflake", provider: "ashby", token: "snowflake" },
  { id: "ashby-clickup", name: "ClickUp", provider: "ashby", token: "clickup" },
  { id: "ashby-vanta", name: "Vanta", provider: "ashby", token: "vanta" },
  { id: "ashby-mural", name: "Mural", provider: "ashby", token: "mural" },
  { id: "ashby-benchling", name: "Benchling", provider: "ashby", token: "benchling" },
  { id: "ashby-langchain", name: "LangChain", provider: "ashby", token: "langchain" },
  { id: "ashby-writer", name: "Writer", provider: "ashby", token: "writer" },
  { id: "ashby-wealthsimple", name: "Wealthsimple", provider: "ashby", token: "wealthsimple" },
  { id: "ashby-ashby", name: "Ashby", provider: "ashby", token: "ashby" },
  { id: "ashby-cohere", name: "Cohere", provider: "ashby", token: "cohere" },
  { id: "ashby-plaid", name: "Plaid", provider: "ashby", token: "plaid" },
  { id: "ashby-sentry", name: "Sentry", provider: "ashby", token: "sentry" },
  { id: "ashby-render", name: "Render", provider: "ashby", token: "render" },
  { id: "ashby-miro", name: "Miro", provider: "ashby", token: "miro" },
  { id: "ashby-thumbtack", name: "Thumbtack", provider: "ashby", token: "thumbtack" },
  { id: "ashby-synthesia", name: "Synthesia", provider: "ashby", token: "synthesia" },
  { id: "ashby-jobber", name: "Jobber", provider: "ashby", token: "jobber" },
  { id: "ashby-1password", name: "1Password", provider: "ashby", token: "1password" },
  { id: "ashby-drata", name: "Drata", provider: "ashby", token: "drata" },
  { id: "ashby-illumio", name: "Illumio", provider: "ashby", token: "illumio" },
  { id: "ashby-nubank", name: "Nubank", provider: "ashby", token: "nubank" },
  { id: "ashby-betterup", name: "BetterUp", provider: "ashby", token: "betterup" },
  { id: "ashby-confluent", name: "Confluent", provider: "ashby", token: "confluent" },
  { id: "ashby-modal", name: "Modal", provider: "ashby", token: "modal" },
  { id: "ashby-iterable", name: "Iterable", provider: "ashby", token: "iterable" },
  { id: "ashby-brightwheel", name: "Brightwheel", provider: "ashby", token: "brightwheel" },
  { id: "ashby-koho", name: "KOHO", provider: "ashby", token: "koho" },
  { id: "ashby-zapier", name: "Zapier", provider: "ashby", token: "zapier" },
  { id: "ashby-klue", name: "Klue", provider: "ashby", token: "klue" },
  { id: "ashby-pinecone", name: "Pinecone", provider: "ashby", token: "pinecone" },
  { id: "ashby-thinkific", name: "Thinkific", provider: "ashby", token: "thinkific" },
  { id: "ashby-wistia", name: "Wistia", provider: "ashby", token: "wistia" },
  { id: "ashby-honeybook", name: "HoneyBook", provider: "ashby", token: "honeybook" },
  { id: "ashby-benevity", name: "Benevity", provider: "ashby", token: "benevity" },
  { id: "ashby-neon", name: "Neon", provider: "ashby", token: "neon" },
  { id: "lever-wattpad", name: "Wattpad", provider: "lever", token: "wattpad" },
  { id: "lever-cloudinary", name: "Cloudinary", provider: "lever", token: "cloudinary" },
  { id: "lever-veeva", name: "Veeva", provider: "lever", token: "veeva" },
  { id: "lever-sonarsource", name: "Sonar", provider: "lever", token: "sonarsource" },
  { id: "lever-aircall", name: "Aircall", provider: "lever", token: "aircall" },
  { id: "lever-pointclickcare", name: "PointClickCare", provider: "lever", token: "pointclickcare" },
  { id: "lever-captivateiq", name: "CaptivateIQ", provider: "lever", token: "captivateiq" },
  { id: "lever-outreach", name: "Outreach", provider: "lever", token: "outreach" },
  { id: "lever-contentsquare", name: "Contentsquare", provider: "lever", token: "contentsquare" },
  { id: "lever-neon", name: "Neon", provider: "lever", token: "neon" },
  { id: "lever-d2l", name: "D2L", provider: "lever", token: "d2l" },
]);

export const ALL_ATS_SOURCES: readonly AtsSource[] = [
  ...CORE_ATS_SOURCES,
  ...DAILY_ATS_SOURCES,
];

export function sourcesForRun(mode: SourceRunMode): readonly AtsSource[] {
  if (mode === "daily") return DAILY_ATS_SOURCES;
  if (mode === "full") return ALL_ATS_SOURCES;
  return CORE_ATS_SOURCES;
}
