export const QUALIFICATION_CONFIG = {
  minimumSalaryCad: 70_000,
  salaryDisplayCeilingCad: 90_000,
  maximumJobAgeDays: 30,
  decayStartHours: 72,
  annualHours: 2_080,
  includeUnknownSalary: true,
  acceptGlobalHybrid: true,
  acceptGlobalOnsite: true,
  includeUnknownWorkType: true,
  targetTitles: [
    "Marketing Manager",
    "Digital Marketing Manager",
    "Growth Marketing Manager",
    "Content Marketing Manager",
    "Brand Marketing Manager",
    "Marketing Communications Manager",
    "Content & Communications Manager",
    "Content Strategy Manager",
    "Content Manager",
    "SEO & GEO Manager",
    "SEO Manager",
    "Marketing Operations Manager",
    "Strategic Marketing Manager",
    "Creative Marketing Manager",
    "Growth & Content Manager",
    "Business Marketing Manager",
    "AI Marketing Manager",
    "AI Marketing Specialist",
    "AI Content Strategist",
    "Content Strategist",
    "Digital Marketing Strategist",
    "Growth Strategist",
    "Content Marketing Specialist",
    "Digital Marketing Specialist",
    "Marketing Communications Specialist",
    "Marketing Lead",
    "Digital Marketing Lead",
    "Content Marketing Lead",
    "Digital Growth Lead",
    "Growth Lead",
    "Head of Content",
  ],
  hybridRegions: [
    { country: "Canada", region: "Ontario" },
    { country: "United States", region: "Florida" },
    { country: "United States", region: "New York" },
  ],
  onsiteCities: [
    { country: "United States", region: "New York", city: "Buffalo" },
    { country: "Canada", region: "Ontario", city: "Hamilton" },
    { country: "Canada", region: "Ontario", city: "Toronto" },
    { country: "Canada", region: "Ontario", city: "Niagara Falls" },
    { country: "Canada", region: "Ontario", city: "St. Catharines" },
    { country: "Canada", region: "Ontario", city: "Niagara-on-the-Lake" },
    { country: "Canada", region: "Ontario", city: "Welland" },
    { country: "Canada", region: "Ontario", city: "Thorold" },
    { country: "Canada", region: "Ontario", city: "Fort Erie" },
    { country: "Canada", region: "Ontario", city: "Port Colborne" },
    { country: "Canada", region: "Ontario", city: "Grimsby" },
    { country: "Canada", region: "Ontario", city: "Lincoln" },
    { country: "Canada", region: "Ontario", city: "Pelham" },
    { country: "Canada", region: "Ontario", city: "West Lincoln" },
  ],
} as const;

export type TargetTitle = (typeof QUALIFICATION_CONFIG.targetTitles)[number];
